"""Setu governance subnet adapter models."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SetuTaskStatus(str, Enum):
    """Lifecycle status of a Setu adapter task."""

    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    NOT_FOUND = "not_found"


class ProposalContent(BaseModel):
    """Setu governance proposal payload forwarded by validator."""

    proposer: str = Field(..., description="Proposal proposer")
    proposal_type: str = Field(..., description="Governance proposal type")
    title: str = Field(..., description="Proposal title")
    description: str = Field(..., description="Proposal description")
    action: Dict[str, Any] = Field(default_factory=dict, description="Proposal effect payload")


class SystemContext(BaseModel):
    """Validator-side system context attached to the request."""

    validator_id: Optional[str] = Field(None, description="Origin validator id")
    subnet_id: Optional[str] = Field(None, description="Optional subnet id hint")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SetuEvaluateRequest(BaseModel):
    """Incoming Setu validator evaluation request."""

    task_id: str = Field(..., description="Task id generated by validator")
    callback_token: str = Field(..., description="Callback token supplied by validator")
    callback_url: str = Field(..., description="Validator callback endpoint")
    proposal: ProposalContent
    system_context: SystemContext = Field(default_factory=SystemContext)


class GovernanceDecision(BaseModel):
    """Decision schema required by Setu governance subnet."""

    approved: bool = Field(..., description="Whether proposal is approved")
    reasoning: str = Field(..., description="Decision reasoning persisted on chain")
    conditions: List[str] = Field(default_factory=list, description="Optional approval conditions")


class EvaluateAcceptedResponse(BaseModel):
    """Immediate acknowledgement response for POST /evaluate."""

    accepted: bool = True
    task_id: str
    status: SetuTaskStatus = SetuTaskStatus.PENDING
    bound_group_id: str
    bound_group_name: str
    subnet_id: str


class SetuResultResponse(BaseModel):
    """Polling response for GET /result/{task_id}."""

    status: SetuTaskStatus
    decision: Optional[GovernanceDecision] = None
    task_id: Optional[str] = None
    consensus_id: Optional[str] = None
    group_id: Optional[str] = None
    subnet_id: Optional[str] = None
    updated_at: Optional[datetime] = None
    error: Optional[str] = None


class SetuTaskRecord(BaseModel):
    """Internal adapter task state used by polling endpoint."""

    task_id: str
    subnet_id: str
    group_id: str
    group_name: str
    callback_token: str
    callback_url: str
    proposal: ProposalContent
    system_context: SystemContext = Field(default_factory=SystemContext)
    status: SetuTaskStatus = SetuTaskStatus.PENDING
    decision: Optional[GovernanceDecision] = None
    consensus_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def mark_updated(self) -> None:
        self.updated_at = datetime.now(timezone.utc)


class SetuTaskStoreSnapshot(BaseModel):
    """Serializable snapshot of persisted Setu adapter runtime state."""

    tasks: List[SetuTaskRecord] = Field(default_factory=list)
    bound_groups: Dict[str, str] = Field(default_factory=dict)
    persisted_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
